version: '3.5'
services:
    setupmongo:
        image: setupmongo
        build: ./setupmongo
        depends_on:      
            - mongonode
        networks:
          - appnetwork
    mongonode:
        hostname: mongonode
        image: mongo:latest
        container_name: mongonode
        volumes:
            - /opt/mongonode/data:/data/db
            - /opt/mongonode/logs:/data/logs
        ports:
            - 27017:27017
        command: [ "/usr/bin/mongod", "--bind_ip_all" ]
        restart: always
        networks:
            - appnetwork
    batch-service:
        image: batch-service
        env_file: .env
        build: ./batch-service
        ports:
            - '8080:8080'
        networks:
            - appnetwork
        depends_on:      
            - setupmongo
networks:
    appnetwork:
        driver: bridge   
        ipam:
            driver: default
