server:
    port: 8080
spring:
    batch:
        job:
            enabled: false
    application:
        name: batch-service
    data:
        mongodb:
            uri: mongodb://${MONGODB_USER:user}:${MONGODB_PASS:pass}@mongonode:27017/batchDB?ssl=false&connectTimeoutMS=300&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&readPreference=primaryPreferred&authSource=admin
